### ISSUE TITLE
您好，我看到了https://documenter.getpostman.com/view/10489749/TVemAp6o#cf8d9077-d929-4a49-add8-b72e81f6112e这边列出很多，我是小白，跑您的code，跑不起来，请问可以发一下最后的code给我学习下吗？谢谢

### ISSUE THREAD

**Issue by ext-beyondcente** [maokofan/portalSite#11]

**Comment by maokofan** [comment]
就是最新的代码呢，报什么错呢

**Comment by ext-beyondcente** [comment]
Error: Could not find or load main class zy.news.NewsApplication
Caused by: java.lang.ClassNotFoundException: zy.news.NewsApplication

**Comment by ext-beyondcente** [comment]
我是用vs code跑的

**Comment by maokofan** [comment]
> Error: Could not find or load main class zy.news.NewsApplication Caused by: java.lang.ClassNotFoundException: zy.news.NewsApplication

这个表示启动时未找到main函数，需要在IDE编译器里进行设置，建议你使用idea运行java maven项目，vs code是运行微软的C#或者.netcore程序的专用，使用其跑java程序觉得怪怪的而且还会出现一些问题，小白不适合

**Comment by maokofan** [comment]
> Error: Could not find or load main class zy.news.NewsApplication Caused by: java.lang.ClassNotFoundException: zy.news.NewsApplication

建议整个程序需要先用maven插件编译一次 然后再运行

**Comment by ext-beyondcente** [comment]
好的，我试试，谢谢啊

**Comment by maokofan** [comment]
^_^

**Comment by ext-beyondcente** [comment]
已经解决了，看了受益匪浅，感谢大神
