### ISSUE TITLE
tmp_share_t表缺失

### ISSUE THREAD

**Issue by ext-beyondcente** [maokofan/portalSite#12]
大神，可以发下tmp_share_t这张表的字段吗？

**Comment by ext-beyondcente** [comment]
Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'tmp_share_t.author' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by maokofan** [comment]
你好 此情况不是tmp_share_t缺失，而是因为数据库版本中默认的sql_mode不相同导致的，需要设置下sql_mode

**Comment by maokofan** [comment]
解决办法参考：https://stackoverflow.com/questions/41887460/select-list-is-not-in-group-by-clause-and-contains-nonaggregated-column-inc

**Comment by maokofan** [comment]
> 大神，可以发下tmp_share_t这张表的字段吗？

tmp_share_t 此表为sql语句中的临时表 你可以全局搜索查看到
