### ISSUE TITLE
添加角色报错

### ISSUE THREAD

**Issue by KING-IRIS** [maokofan/portalSite#2]
![761582855851_ pic_hd](https://user-images.githubusercontent.com/61318679/75504794-6d6e1c80-5a14-11ea-9081-a2393306cb02.jpg)

**Comment by maokofan** [comment]
<select id="selectRoleByName" resultType="zy.news.web.bean.SysRole">
        select  count(*) from t_sys_role t
        where t.role=#{role,jdbcType=VARCHAR}
    </select>
返回resultType类型错误
